### ISSUE TITLE
Fastlane

### ISSUE THREAD

**Issue by IzzySoft** [petabyt/fudge#10]
Glad to see you've established Fastlane structures here! Would you mind some "enhancements" there? If you take a look at [your app in my repo](https://apt.izzysoft.de/packages/dev.danielc.fujiapp/) you'll see it has an icon, some additional screenshots – and a more detailed `full_description`, also in German. You're welcome to copy from there – or let me know which parts I should send via a PR. Thanks in advance!

**Comment by petabyt** [comment]
That was the initial description I guess you copied from Google Play, I made the mistake of going a little overboard insulting Fujifilm's apps. Degrading Fujifilm is not a goal for this project. (And a bad idea in general)

If you can just copy the full_description I have in the repo now that would be great. Thanks man.

**Comment by IzzySoft** [comment]
> That was the initial description I guess you copied from Google Play

Yupp. At the time I set up your app in my repo, fastlane did not yet exist, so initial data were copied from Play.

> If you can just copy the full_description I have in the repo now

Sure, and fully understood – will be done! Will you add an icon here and maybe additional screenshots (initial ones in my repo again were taken from your PlayStore listing)?

**Comment by petabyt** [comment]
Will do, thanks man. There's screenshots, I'll probably update them soon. Gonna do a new hopefully soon.

**Comment by IzzySoft** [comment]
> There's screenshots in the fastlane folder

Yes, I've seen them: 3 screenshots. I can enable pulling them from fastlane to my repo – but there are currently 5, so 2 would be lost. Just let me know when I shall enable that. Thanks!

**Comment by petabyt** [comment]
There's not much to look at in this app. 3 screenshots are fine for now.

**Comment by IzzySoft** [comment]
As you wish. With the next update, they'll be replaced then: I've just enabled screenshots and icon in Fastlane here. Thanks!
