### ISSUE TITLE
App does not work with X-T2

### ISSUE THREAD

**Issue by edern-appere** [petabyt/fudge#11]
Hi !

I tested your app with my Fuji X-T2 but could not make a connection between the two devices. I guess Fuji implemented a different protocol for each camera depending on hardware ?

BTW, if you want me to test some stuff to make the app work, or send logs, let me know !

Bye

**Comment by petabyt** [comment]
Hi, thanks for testing it. With the latest version I was able to get it working reliably on the X-H1. I don't think the X-T2 is much different but Fuji might have thrown in some annoying abstraction that breaks Fudge.
What error did you get? You can run the test suite (top right button on the toolbar) and it will log some more info

**Comment by petabyt** [comment]
Found likely cause of issue, will fix soon
