### ISSUE TITLE
Fujifilm X30 connection establishment issue

### ISSUE THREAD

**Issue by stsdc** [petabyt/fudge#12]
Managed to connect only after i manually chose the Fuji AP and connected to it.

After that, the camera display showed the confirmation question about connecting to Fudge and hanged. Had to press the Play button, so it exited the wireless mode.

On app view it showed this:
![Screenshot_20240408-152804.png](https://github.com/petabyt/fudge/assets/6031763/5892e559-41e0-4718-8328-94101bfa13a2)

Let me know if you need more logs 👍

**Comment by petabyt** [comment]
> Managed to connect only after i manually chose the Fuji AP and connected to it.

This is normal behavior, but now that you mention it, this might need to be more clear in the app.

> Let me know if you need more logs 👍

If you want you can try the regression tester (it's the checklist button on top right). It will do some checks once you connect to the camera and try to get some basic things to work.

X30 might be tricky to implement because that was when Fuji had first implemented 'remote mode' (liveview shooting. Fudge currently doesn't have remote mode working (soon it will) but if a camera has remote mode, you have to go through a long setup process to get it ready for just the image gallery. Fuji's first few versions of this may have different behavior compared to what I'm testing (X-H1)

**Comment by stsdc** [comment]
Yeah, it wasn't obvious that i should manually connect to the AP. Also, the app isn't picking up wifi connection when LTE is enabled. So I had to disable it 😬

Here are some logs.
```
ABI: arm64-v8a
Compile date: Mar  2 2024
https://github.com/petabyt/fudge
Running test suite from C
Initialized command socket
Connected to X30
sleep 500ms for good measure...
send_bulk_packet: Sent 16/16 bytes
ptpipusb_receive_bulk_packets: Read 12 bytes
ptpipusb_receive_bulk_packets: Return code: 0x2001
Opened session
Waiting for device access...
send_bulk_packet: Sent 16/16 bytes
ptpipusb_receive_bulk_packets: Read 62 bytes
ptpipusb_receive_bulk_packets: Return code: 0x2001
Found 6 events
DF00 changed to 6
D220 changed to 1
D222 changed to 44
D52F changed to 1
D400 changed to 1
D401 changed to 44
Gained access to device (or already have access)
Configuring mode property
send_bulk_packet: Sent 16/16 bytes
ptpipusb_receive_bulk_packets: Read 28 bytes
ptpipusb_receive_bulk_packets: Return code: 0x2001
GetObjectVersion: 0x3send_bulk_packet: Sent 16/16 bytes
ptpipusb_receive_bulk_packets: Read 28 bytes
ptpipusb_receive_bulk_packets: Return code: 0x2001
RemoteGetObjectVersion: 0x1send_bulk_packet: Sent 16/16 bytes
ptpipusb_receive_bulk_packets: Read 28 bytes
ptpipusb_receive_bulk_packets: Return code: 0x2001
ImageGetVersion: 0x3send_bulk_packet: Sent 16/16 bytes
ptpipusb_receive_bulk_packets: Read 28 bytes
ptpipusb_receive_bulk_packets: Return code: 0x2001
RemoteVersion: 0x20002CameraState is 6Setting mode to 5send_bulk_packet: Sent 16/16 bytes
send_bulk_packet: Sent 14/14 bytes
ptpipusb_receive_bulk_packets: Read 12 bytes
ptpipusb_receive_bulk_packets: Return code: 0x2001
Mode property is configured.
Configuring version properties
RemoteVersion was 20002
send_bulk_packet: Sent 16/16 bytes
send_bulk_packet: Sent 16/16 bytes
ptpipusb_receive_bulk_packets: Read 8 bytes
ptpipusb_receive_bulk_packets: Return code: 0xFFFF
Failed to configure FunctionMode: -8
```

**Comment by petabyt** [comment]
> Yeah, it wasn't obvious that i should manually connect to the AP.

Thanks for the feedback, I'll think about improving it.

> Also, the app isn't picking up wifi connection when LTE is enabled. So I had to disable it 

Only thing I can think of that could cause this is the delay after connecting to the access point. On my phone (Pixel, Android 14) it takes about 5-10 seconds until a connection established or (No internet access) notification shows up.
Fudge is directly listening to the system's WiFi events (`ConnectivityManager.NetworkCallback`) so it should be telling the app when WiFi connection is established/disconnected, unless it isn't...

> Is the copied log enriched with more data compared to what is shown on the view? Bc it would be nice to see exactly what will be copied 👍

It has some verbose communication logs (`ptp_verbose_log`). Normally it's disabled but it routes to a buffer in the test suite.

And thanks for the logs. I'll stick some of the numbers in my Fuji camera emulator and see what Fuji's app does this weekend.

**Comment by petabyt** [comment]
I can reproduce the issue in vcam, cam is hanging and not returning a response after setting RemoteVersion. So issue is either:
- Timing issue (camera freaks out)
- We are setting wrong RemoteVersion -> Camera hangs and refuses to do anything else
- Camera needs you to press OK button before getting response

I've never had any of these issues on my X-H1.

**Comment by stsdc** [comment]
Well, I can only confirm that pressing OK does nothing. If there are any non invasive methods, that can push this issue forward, I would like to help.

**Comment by petabyt** [comment]
I'm able to reproduce the issue, will push a fix soon
Cause is Android TCP NODELAY weirdness, will need a deeper investigation on why the camera is not accepting the packets.

**Comment by petabyt** [comment]
Fixed https://github.com/petabyt/fudge/commit/04b80cab354989c81fbaea09b0842f8d02757a40
