### ISSUE TITLE
Size and resolution differes between app and camera

### ISSUE THREAD

**Issue by stsdc** [petabyt/fudge#15]
Not sure if I forgot to set some setting, or this is just how Fuji protocol works or app itself.
But it downloads also a smaller image.

![image](https://github.com/petabyt/fudge/assets/6031763/676891e7-21d5-4165-8ed1-acdb27e2561d)
![Untitled](https://github.com/petabyt/fudge/assets/6031763/a8ecef6d-a73c-41f5-b27a-fbe2d61990e9)

**Comment by petabyt** [comment]
In connection settings there an option 'RESIZE IMAGE FOR SMARTPHONE', turn it off and it will download full size.

**Comment by stsdc** [comment]
Thank you!
