### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by LucasGGamerM** [petabyt/fudge#18]
I have been having a bunch of bad experiences with the Fuji Camera remote app and my X-H1. I just discovered your app, and it is so far a lot more reliable (and it's open source!)

Where can I throw a couple of bucks at you?

**Comment by petabyt** [comment]
Thanks but this project doesn't need money (it's well funded, a 'Thank you' would be enough to put a smile on my face :)). If you still want to leave a tip it looks like the ligjpeg-turbo accepts paypal donations. GIMP and any of the other open-source RAW/image processing software also be just as good.

**Comment by LucasGGamerM** [comment]
Then I will give you my thank you! I will keep that in mind. 

Thank you for making my Fuji system not be dependant on a (shitty) proprietary app 🥰🥰🥰
