### ISSUE TITLE
Would like to contribute for X100F compatibility

### ISSUE THREAD

**Issue by joshmalek** [petabyt/fudge#19]
Hey @petabyt,
Love to see the work you've done so far, my frustration has always been with how crash-prone the original FUJI camera app has been especially with my X100F.  I'd like to contribute to this, my overall goal would be basically to get a button to fast-import all photos that have been taken since the last import, with as little overhead as possible.  Basically skipping the garbage having to go through all photos in the grid and select each one piece by piece to import. I have basically no familiarity with how the protocols you're using to interact with the cameras or if you even support the x100F yet, but please let me know any way I can get this set up.  Or if you have some time to meet to discuss the implementation that would be cool too.

Thanks again for your hard work!

**Comment by petabyt** [comment]
> I'd like to contribute to this, my overall goal would be basically to get a button to fast-import all photos that have been taken since the last import, with as little overhead as possible.

I haven't heard this before. For me I normally just want to download a photo or two after taking it to share. Nonetheless, a very valid request.

Right now I'm working on replacing PC AutoSave functionality (and wireless tether) which works the best for exactly what you describe, but both devices have to be connected to an WiFi network. I don't know if that sounds good to you but I can definitely add backup to both autosave and regular wifi pairing.

**Comment by petabyt** [comment]
Also your camera might have a "multiple transfer" mode, where you can select the images on your camera and it will automatically download on once you connect to the app. My 2015 X-A2 has it.

**Comment by petabyt** [comment]
Closed, inactive
