### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by LucasGGamerM** [petabyt/fudge#20]
I have been trying to build the project from source, but I haven't managed to get around this error in Android Studio:

```
No matching configuration of project :libui was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.4.2' but:
          - None of the consumable configurations have attributes.
```

**Comment by petabyt** [comment]
There's no stable release right now, so it won't build, sorry. It looks like you forgot to clone with `--recurse-submodules`. I'm in the middle of making some major changes. I'll probably be done by the end of this month.

**Comment by LucasGGamerM** [comment]
Btw it seems like petabyt/android-libjpeg-turbo is a private repo, but it's in the submodules, so it just refuses to clone :(

**Comment by petabyt** [comment]
Is it? https://github.com/petabyt/android-libjpeg-turbo

**Comment by LucasGGamerM** [comment]
Hmmmm..... Sorry for the confusion, although I'd still recommend a build instructions section under the readme. I am not in my PC right now to test this properly, but I will see if I can make this work and eventually contribute a nice build section for this app's readme. 

Also thank you for your work! (I saw on the website that the app was tested on an X-H1, did you get one since last time?)

**Comment by petabyt** [comment]
Sorry but the build is currently failing: https://github.com/petabyt/fudge/actions/runs/9932742288/job/27434490136
I'll be sure to get it working before the next release (should be done by at least August 31st)

Yes, it works on my X-H1 among a few other tested models. Just the gallery and photo downloading for now. Liveview and stuff will come later.

**Comment by LucasGGamerM** [comment]
> Sorry but the build is currently failing: https://github.com/petabyt/fudge/actions/runs/9932742288/job/27434490136 I'll be sure to get it working before the next release (should be done by at least August 31st)
> 
> Yes, it works on my X-H1 among a few other tested models. Just the gallery and photo downloading for now. Liveview and stuff will come later.

I got myself and X-H1 as well. It's such a nice camera! Anyhow, I got it to build by commenting out some code, but I shall wait for a fix and for the other major thing before I start working on my own improvements for this app :D

**Comment by petabyt** [comment]
Build is working again: https://github.com/petabyt/fudge/actions/runs/10232659465/job/28310056465
