### ISSUE TITLE
Features request - geolocation and raw processing

### ISSUE THREAD

**Issue by gullmar** [petabyt/fudge#21]
Firstly, thanks for your work and for making it open source.
I tested it with an X-T30 (mark 1) and I can confirm it works.

I would like to suggest two features, for future development, that I would really appreciate. This is more a discussion/proposal than an actual issue, so please discard it if you don't consider it appropriate, or you're not willing to accept such requests.

The features are the following:

1. Allow geolocating pictures using phone's GPS whenever the Bluetooth connection will be implemented. This is actually the main reason why I keep the Fuji app installed on my smartphone, other than firmware updates. I encountered battery drain problems, tho, which I can only solve by force killing the app and re-opening it. It would be amazing to have an open source alternative for this.
2. Allow processing RAW files using the camera's engine, like “FUJIFILM X RAW STUDIO” does. This may be out of scope, because it is not a feature of the official Android app, but of another desktop app, instead. The latter is quite slow, is missing many features, like bulk editing, and doesn't support Linux. Since you have already implemented USB/OTG and plan to create a desktop/app utility, I thought it could be a feature to reason about, but I really have no idea.

That's it. Thank you again for this software.

**Comment by petabyt** [comment]
> Allow geolocating pictures using phone's GPS whenever the Bluetooth connection will be implemented.

Duly noted

> Allow processing RAW files using the camera's engine, like “FUJIFILM X RAW STUDIO” does.

I think that would be out of scope for the android app (although not for the desktop app). For processing RAWs I would rather have a separate app similar to lightroom/darktable than having to connect to a camera to use it's image processor. But that's probably not something I'll work on, at least anytime soon.

**Comment by gullmar** [comment]
Thank you for considering these suggestions.

Regarding the second point: I agree that for having a proper workflow, one should look at RAW editors such as Lightroom and Darktable.
The catch of X RAW STUDIO is that it allows you to quickly convert raw pictures to JPG, changing settings such as exposure compensation and Fuji film simulation, which is superb, as if a picture was taken on camera with those settings.
You could actually do the same thing, pressing Q while looking at an existing picture on your camera: handy, but a bit inconvenient if you want to convert a lot of pictures, because it takes a lot of time, and you are limited by a small screen.

The point is that X RAW STUDIO, which would allow doing this on a computer, is quite bad: that's why I would love to see an open source alternative.

That said, now that I think about it, implementing such a feature would probably require reverse engineering the USB connection between the computer and the camera, and it would be greatly out of scope for this project.

**Comment by petabyt** [comment]
I get the benefits of raw studio, but to me it seems like a lazy move by Fuji, and I don't blame them. It's much easier to use the camera's image processor than to create an editing engine.
At the end of the day, if I had to create a raw editor myself, I would rather invest in a engine more capable than the processing chip in a camera.
But I wouldn't be opposed to having it as a CLI feature if ends up being useful. But just making the frontend would be a huge pain.

**Comment by gullmar** [comment]
I agree, if the frontend part was too hard to implement, having a CLI would still be a big step forward.

**Comment by gkoh** [comment]
@petabyt Apologies in advance, I follow your project with great interest and do not intend to hijack it. I will happily wipe this comment if you deem it inappropriate.

@gullmar For your GPS use case, you may be interested in my project: https://github.com/gkoh/furble

**Comment by petabyt** [comment]
@gkoh No problem at all! I don't have the right hardware but I'm a fan of furble. I've been closely watching it.

**Comment by petabyt** [comment]
By the way, bluetooth integration in Fudge is on the roadmap. I don't know if I'll ever get to finishing it but I intend to first implement a virtual camera (same as I did for PTP/IP https://github.com/petabyt/vcam). That might help us both out.

**Comment by gkoh** [comment]
> By the way, bluetooth integration in Fudge is on the roadmap. I don't know if I'll ever get to finishing it but I intend to first implement a virtual camera (same as I did for PTP/IP https://github.com/petabyt/vcam). That might help us both out.

Indeed! I will monitor with interest.

This belongs in a discussion (to avoid diluting this issue), however I do wonder if furble's backend could be used in fudge.
The challenge is furble's bluetooth stack is quite coupled to the ESP32 bluetooth library, although it could be abstracted away with some effort.

At a minimum I should really document the reverse engineering I've done on the Fujifilm bluetooth, so it can be reimplemented at will.

**Comment by petabyt** [comment]
I've been planning on using this library: https://github.com/OpenBluetoothToolbox/SimpleBLE so that it could be portable across iOS/Android.

You can join the Fujihack discord if you want, we talk about camera hacking and reversing: https://discord.gg/UZXDktvAZP

**Comment by gullmar** [comment]
> @gullmar For your GPS use case, you may be interested in my project: https://github.com/gkoh/furble

Thank you, I will try it out.
I think I'll be following both projects!

**Comment by petabyt** [comment]
Update on raw processing:

![Image](https://github.com/user-attachments/assets/616bfd14-a9d8-418b-81db-69ccd2f1f1b8)

Got my first raw image processed by fudge after reverse-engineering the profile formats.

**Comment by gullmar** [comment]
This is great! I'm still not aware of any 3rd party software which is able to do this.

**Comment by petabyt** [comment]
Raw conversion solved https://fudge.danielc.dev/blog/3

**Comment by gullmar** [comment]
Huge news, thank you very much! I will test it as soon as possible! 😄
