### ISSUE TITLE
Failed to open session X-T2

### ISSUE THREAD

**Issue by NXij** [petabyt/fudge#4]
Fujiapp log file - Send this to devs!
ABI: arm64-v8a
Compile date: Jul 11 2023
https://github.com/petabyt/fujiapp
Running test suite from C
send_bulk_packets 0x1002 (PTP_OC_OpenSession)
send_bulk_packet: Sent 16 bytes
Failed to read 8 bytes
Failed to open session

When I try to connect again a few times it'll appear as if its working

Fujiapp log file - Send this to devs!
ABI: arm64-v8a
Compile date: Jul 11 2023
https://github.com/petabyt/fujiapp
Running test suite from C
send_bulk_packets 0x1002 (PTP_OC_OpenSession)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 12 bytes
recieve_bulk_packets: Return code: 0x2001
Opened session
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 62 bytes
recieve_bulk_packets: Return code: 0x2001
Recieved events after opening session.
Payload: 06 00 00 DF 06 00 00 00 20 D2 01 00 00 00 22 D2 7B 00 00 00 2F D5 01 00 00 00 00 D4 01 00 00 00 01 D4 7B 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 26 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF00 (2 bytes)
Payload: 06 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 26 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF01 (2 bytes)
Payload: 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF21 (4 bytes)
Payload: 03 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF22 (4 bytes)
Payload: 04 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF23 (4 bytes)
Payload: 01 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF24 (4 bytes)
Payload: 04 00 02 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF25 (4 bytes)
Payload: 02 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 24 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF26 (0 bytes)
No payload
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF31 (4 bytes)
Payload: 02 00 00 00 
Waiting for device access...
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 26 bytes
recieve_bulk_packets: Return code: 0x2001
send_bulk_packets 0x1016 (PTP_OC_SetDevicePropValue)
send_bulk_packet: Sent 16 bytes
send_bulk_packets 0xB (PTPIP_CANCEL_TRANSACTION)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 12 bytes
recieve_bulk_packets: Return code: 0x2001
Gained access to device (or already have access)
Configuring mode property
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 26 bytes
recieve_bulk_packets: Return code: 0x2001
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Version uint32 was 20004
send_bulk_packets 0x1016 (PTP_OC_SetDevicePropValue)
send_bulk_packet: Sent 16 bytes
send_bulk_packets 0x2001 (PTP_RC_OK)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 12 bytes
recieve_bulk_packets: Return code: 0x2001
Mode property is configured.
Configuring FunctionMode
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
send_bulk_packets 0x1016 (PTP_OC_SetDevicePropValue)
send_bulk_packet: Sent 16 bytes
send_bulk_packets 0x2001 (PTP_RC_OK)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 12 bytes
recieve_bulk_packets: Return code: 0x2001
Configured FunctionMode, no errors detected (yet)
Trying to get SD card info...
send_bulk_packets 0x1004 (PTP_OC_GetStorageIDs)
send_bulk_packet: Sent 12 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
No storage devices found!
We got to the end of the test, and nothing broke :)
Ending test...

Trying to connect again after this results in Failed to init socket
The OS on the camera stays on the app connection init screen as if nothing had happened

**Comment by petabyt** [comment]
I there there might be a timing issue, I've seen that a few times. The second test looks perfect, apart from the fact that it didn't get any storage devices. You have an SD card in it right?

**Comment by NXij** [comment]
Yep, the SD card is there (Sony UHS-II)

**Comment by NXij** [comment]
Fujiapp log file - Send this to devs!
ABI: arm64-v8a
Compile date: Jul 25 2023
https://github.com/petabyt/fujiapp
Running test suite from C
Initialized command socket
Connected to X-T2
- Supports gps
sleep 500ms for good measure...
send_bulk_packets 0x1002 (PTP_OC_OpenSession)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 12 bytes
recieve_bulk_packets: Return code: 0x2001
Opened session
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 62 bytes
recieve_bulk_packets: Return code: 0x2001
Found 6 events
DF00 changed to 6
D220 changed to 1
D222 changed to 123
D52F changed to 1
D400 changed to 1
D401 changed to 123
Recieved events after opening session.
Payload: 06 00 00 DF 06 00 00 00 20 D2 01 00 00 00 22 D2 7B 00 00 00 2F D5 01 00 00 00 00 D4 01 00 00 00 01 D4 7B 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 26 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF00 PTP_PC_FUJI_Unlocked (2 bytes)
Payload: 06 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 26 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF01 PTP_PC_FUJI_Mode (2 bytes)
Payload: 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF21 PTP_PC_FUJI_PhotoGetVersion (4 bytes)
Payload: 03 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF22 PTP_PC_FUJI_FunctionVersion (4 bytes)
Payload: 04 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF23 PTP_PC_FUJI_Unknown10 (4 bytes)
Payload: 01 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF24 PTP_PC_FUJI_RemoteVersion (4 bytes)
Payload: 04 00 02 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF25 PTP_PC_FUJI_RemotePhotoViewVersion (4 bytes)
Payload: 02 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 24 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF26 PTP_PC_FUJI_PhotoRecieveReservedVersion (0 bytes)
No payload
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xDF31 PTP_PC_FUJI_VersionGPS (4 bytes)
Payload: 02 00 00 00 
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 24 bytes
recieve_bulk_packets: Return code: 0x2001
Read property 0xD235 PTP_PC_FUJI_PartialSize (0 bytes)
No payload
Waiting for device access...
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 26 bytes
recieve_bulk_packets: Return code: 0x2001
unlocked_mode: 6
Gained access to device (or already have access)
Configuring mode property
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
Unlocked mode is 6
Setting mode to 5
send_bulk_packets 0x1016 (PTP_OC_SetDevicePropValue)
send_bulk_packet: Sent 16 bytes
send_bulk_packets 0x2001 (PTP_RC_OK)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 12 bytes
recieve_bulk_packets: Return code: 0x2001
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
RemoteVersion was 20004
send_bulk_packets 0x1016 (PTP_OC_SetDevicePropValue)
send_bulk_packet: Sent 16 bytes
send_bulk_packets 0x2001 (PTP_RC_OK)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 12 bytes
recieve_bulk_packets: Return code: 0x2001
Mode property is configured.
Configuring FunctionMode
send_bulk_packets 0x1015 (PTP_OC_GetDevicePropValue)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
send_bulk_packets 0x1016 (PTP_OC_SetDevicePropValue)
send_bulk_packet: Sent 16 bytes
send_bulk_packets 0x2001 (PTP_RC_OK)
send_bulk_packet: Sent 16 bytes
recieve_bulk_packets: Read 12 bytes
recieve_bulk_packets: Return code: 0x2001
Configured FunctionMode, no errors detected (yet)
Device passed device info routine
Configured remote photo viewer
Trying to get SD card info...
send_bulk_packets 0x1004 (PTP_OC_GetStorageIDs)
send_bulk_packet: Sent 12 bytes
recieve_bulk_packets: Read 28 bytes
recieve_bulk_packets: Return code: 0x2001
No storage devices found!
We got to the end of the test, and nothing broke :)
Ending test...

**Comment by petabyt** [comment]
Yep, currently working on that one, camera does non standard stuff I didn't expect
