### ISSUE TITLE
XT-20 Failed to configure mode with camera

### ISSUE THREAD

**Issue by ThatOneCalculator** [petabyt/fudge#6]
Camera gets stuck here, "Ok" button does nothing

![PXL_20230819_150020917.jpg](https://github.com/petabyt/fudge/assets/44733677/08725230-dbf3-43b2-99ca-1f8549dea9d1)

![Screenshot_20230819-080010.png](https://github.com/petabyt/fudge/assets/44733677/45f7a3b0-9dd5-49d0-8ac8-60ebb5c35525)

**Comment by ThatOneCalculator** [comment]
Logs

![Screenshot_20230819-080306.png](https://github.com/petabyt/fudge/assets/44733677/2a3bda9d-c007-48bd-bc8b-04fa9036c073)

**Comment by petabyt** [comment]
Seems to work perfectly until setting up mode, the X-T20 seems to specifically want nothing to do with it.

**Comment by ThatOneCalculator** [comment]
Is there anything I can do to help? I saw on the readme wifi packet dumps are needed, if there's a guide on how to do that, I'd happily contribute.

**Comment by petabyt** [comment]
I've managed to get https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture&hl=en_US&gl=US to sniff TCP packets from the old app, but it takes a ton of fiddling to get it to work.

The steps I had wrote down were:
```
Connect to wifi
open capture app
start record for fuji app
open fuji app
try connection
close app
restart connection
open app again
```

The alternative to sniffing packets for every protocol version, (which I think there are 7) is creating a Fuji camera emulator server to communicate with Fujifilm's apps, and then try on Fudge once it's stable.

**Comment by ThatOneCalculator** [comment]
Wait, was this fixed? I haven't had a chance to do the steps yet.

**Comment by petabyt** [comment]
Not fixed yet. Although I've chosen the X-T20 to implement in my reverse-engineered camera emulator server, and will be trying Fujifilm's Camera Connect app on it. Should have a fix shortly.

**Comment by petabyt** [comment]
Did you turn on WiFi from the camera? Or did you use Bluetooth first and Fuji's app to activate the wireless AP?

**Comment by ThatOneCalculator** [comment]
Wifi from the camera. Afaik, the XT-20 doesn't have Bluetooth, as that was added with the XT-3/30
