### ISSUE TITLE
storage permissions

### ISSUE THREAD

**Issue by IzzySoft** [petabyt/fudge#9]
My recently upgraded scanner today reports on your update:

    ! repo/dev.danielc.fujiapp_5.apk declares risky permission(s): android.permission.READ_EXTERNAL_STORAGE*

This is an "implied permission" (Android automatically grants that when `WRITE_EXTERNAL_STORAGE` is requested. Seeing that one needs at least Android 5 to run your app, and that there's SAF (Storage Access Framework) available to deal with file system operations: Does your app really need that permission (and what for then), or could it be dropped?

Thanks in advance for clarification!

**Comment by petabyt** [comment]
Maybe it's a redundant permission, but the app needs to write JPEGs to `DCIM/fuji` (and create the `DCIM/fuji` folder, and that's it. I did it the way I've always remembered doing it.

**Comment by IzzySoft** [comment]
I'd say that's what `READ_MEDIA_STORAGE` and `WRITE_MEDIA_STORAGE`  are for with "scoped storage". But maybe only up to Android 10. They changed that too often, hard to keep track :see_no_evil: The proper documentation [should be here](https://developer.android.com/training/data-storage/shared/media) – and that says you need `*_EXTERNAL_STORAGE` only to access files created by other apps.

So maybe your app only needs `READ_MEDIA_IMAGES` and `WRITE_MEDIA_IMAGES`? But there we go:

> If your app is used on a device that runs Android 9 or lower, or if your app has temporarily [opted out of scoped storage](https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage), you must request the [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE) permission to access any media file. If you want to modify media files, you must request the [WRITE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE) permission, as well.

OK, that answers my question: a device with Android 5 would be "a device that runs Android 9 or lower". Thanks, learned a new thing again. And apologies for the false alert then! I've put it on the allow-list for your app now:

```yaml
    PermIgnore:
      android.permission.READ_EXTERNAL_STORAGE: This permission was granted implicitly as WRITE_EXTERNAL_STORAGE was requested, which is needed to access media files on Android 9 and below.
```
